modLoader = "javafml"
loaderVersion = "[35,]"
license = "MIT License"
issueTrackerURL = "https://github.com/SocketMods/BanMallet/issues"

[[mods]]
modId = "banmallet"
version = "${file.jarVersion}"
displayName = "BanMallet"
displayURL = "https://socketsmod.dev/"
authors = "The team at SocketMods"
description = """
Small improvements and additions to the Minecraft moderation toolset.
"""

[[dependencies.banmallet]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.banmallet]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.4,1.17)"
ordering = "NONE"
side = "BOTH"